Repository quictls/quictls, pull requests merged in 2025-01, with the labels that each got.

#189 Rm sxnet nss
  CHANGES.md
  apps/build.info
  apps/nseq.c
  crypto/asn1/asn1_item_list.h
  crypto/asn1/build.info
  crypto/asn1/nsseq.c
  crypto/pem/pem_all.c
  crypto/x509/build.info
  crypto/x509/ext_dat.h
  crypto/x509/standard_exts.h
  crypto/x509/v3_sxnet.c
  doc/man3/PEM_read_CMS.pod
  doc/man3/X509V3_get_d2i.pod
  doc/man3/X509_dup.pod
  doc/man3/d2i_X509.pod
  fuzz/asn1.c
  include/apps/apps.h
  include/openssl/cryptoerr_legacy.h
  include/openssl/pem.h
  include/openssl/x509.h.in
  include/openssl/x509v3.h.in
  test/recipes/25-test_req.t
  util/indent.pro
  util/libcrypto.num
  util/missing.txt
Labels: trivial

#188 Document RSA-PSS DER output change
  doc/man7/RSA-PSS.pod
Labels: trivial

#192 Remove file referenece missed in #182
  ssl/ssl_local.h
Labels: trivial, build-break

#197 Doc fixes 2
  doc/build.info
  doc/man7/crypto.pod
  doc/man7/fips_module.pod
  doc/man7/migration-guide.pod
  doc/man7/ossl-guide-introduction.pod
  doc/man7/ossl-guide-libraries-introduction.pod
  doc/man7/ossl-guide-tls-client-block.pod
  doc/man7/ossl-guide-tls-client-non-block.pod
  doc/man7/ossl-guide-tls-introduction.pod
  doc/man7/ssl.pod
Labels: cmake-prep

#165 Remove ERRxxx() defines, various old doc files
  .gitignore
  CHANGES.md
  build.info
  crypto/ec/ecp_sm2p256.c
  crypto/err/err_all.c
  crypto/sm2/sm2_sign.c
  doc/HOWTO/certificates.txt
  doc/HOWTO/keys.txt
  doc/README.md
  doc/designs/fetching-composite-algorithms.md
  doc/designs/ossl-provider-load-ex.md
  doc/designs/passing-algorithmidentifier-parameters.md
  doc/designs/thread-api.md
  doc/designs/xof.md
  doc/dir-locals.example.el
  doc/fingerprints.txt
  doc/images/openssl-square-nontransparent.png
  doc/images/openssl-square.svg
  doc/images/openssl.svg
  doc/internal/documenting-functions-and-macros.md
  doc/life-cycles/Makefile
  doc/life-cycles/README.md
  doc/life-cycles/cipher.dot
  doc/life-cycles/digest.dot
  doc/life-cycles/kdf.dot
  doc/life-cycles/lifecycles.ods
  doc/life-cycles/mac.dot
  doc/life-cycles/pkey.dot
  doc/life-cycles/rand.dot
  doc/openssl-c-indent.el
  exporters/build.info
  exporters/libcrypto.pc.in
  exporters/libssl.pc.in
  exporters/mkinstalldata.pl
  exporters/openssl.pc.in
  include/openssl/err.h.in
  providers/implementations/ciphers/cipher_aes_ocb.c
  util/err-to-raise
  util/fix-deprecation
  util/merge-err-lines
  util/missingmacro.txt
  util/missingssl.txt
  util/su-filter.pl
  util/withlibctx.pl
Labels: trivial

#167 Remove some old source3 and doc
  crypto/LPdir_nyi.c
  test/json_test.c
Labels: trivial

#166 Replace perl template with custom script for headers
  Configurations/unix-Makefile.tmpl
  Configurations/windows-makefile.tmpl
  build.info
  include/mkhdr.pl
  include/openssl/asn1.h.gen
  include/openssl/asn1t.h.gen
  include/openssl/bio.h.gen
  include/openssl/cmp.h.gen
  include/openssl/cms.h.gen
  include/openssl/conf.h.gen
  include/openssl/crmf.h.gen
  include/openssl/crypto.h.gen
  include/openssl/ct.h.gen
  include/openssl/err.h.gen
  include/openssl/ess.h.gen
  include/openssl/lhash.h.gen
  include/openssl/ocsp.h.gen
  include/openssl/pkcs12.h.gen
  include/openssl/pkcs7.h.gen
  include/openssl/safestack.h.gen
  include/openssl/ssl.h.gen
  include/openssl/ui.h.gen
  include/openssl/x509.h.gen
  include/openssl/x509_vfy.h.gen
  include/openssl/x509v3.h.gen
  util/mknum.pl
Labels: cmake-prep

#200 Update authors, now that we have some.
  AUTHORS.md
  README.md
Labels: trivial

#209 Simplify wording in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: trivial

#211 Set copyright year in generated files
  crypto/asn1/charmap.h
  crypto/asn1/charmap.pl
  crypto/conf/keysets.pl
  crypto/objects/obj_dat.h
  crypto/objects/obj_dat.pl
  crypto/objects/obj_xref.h
  crypto/objects/objects.pl
  crypto/objects/objxref.pl
  fuzz/mkfuzzoids.pl
  fuzz/oids.txt
  include/openssl/obj_mac.h
  util/perl/OpenSSL/copyright.pm
Labels: trivial

#212 Centralize internal doc files
  doc/internal/engine-table.md
  doc/internal/notes/documenting-functions-and-macros.md
  doc/internal/notes/tls-state-machine.md
  doc/internal/objects-oids.md
  doc/internal/perlasm.md
  doc/internal/property-queries.md
  doc/internal/sparse-array.md
Labels: trivial

#213 Remove libfips from build.info files
  crypto/aes/build.info
  crypto/bn/build.info
  crypto/buffer/build.info
  crypto/build.info
  crypto/cmac/build.info
  crypto/des/build.info
  crypto/dh/build.info
  crypto/dsa/build.info
  crypto/ec/build.info
  crypto/evp/build.info
  crypto/ffc/build.info
  crypto/hmac/build.info
  crypto/lhash/build.info
  crypto/modes/build.info
  crypto/property/build.info
  crypto/rand/build.info
  crypto/rsa/build.info
  crypto/sha/build.info
  crypto/sm4/build.info
  crypto/stack/build.info
  crypto/thread/build.info
  providers/build.info
  providers/common/build.info
  providers/common/der/build.info
  providers/fips/build.info
  providers/fips/fips_entry.c
  providers/fips/fipsprov.c
  providers/fips/self_test.c
  providers/fips/self_test.h
  providers/fips/self_test_data.inc
  providers/fips/self_test_kats.c
  providers/implementations/asymciphers/build.info
  providers/implementations/ciphers/build.info
  providers/implementations/digests/build.info
  providers/implementations/exchange/build.info
  providers/implementations/kdfs/build.info
  providers/implementations/kem/build.info
  providers/implementations/keymgmt/build.info
  providers/implementations/macs/build.info
  providers/implementations/rands/build.info
  providers/implementations/signature/build.info
  ssl/record/methods/build.info
Labels: trivial

#215 Suppress -Wswitch-default, at least for now
  Configure
Labels: trivial

#214 Mv bn int doc
  doc/internal/man3/bn_mul_words.pod
Labels: trivial

#217 One more bn_print
  doc/internal/man3/bn_mul_words.pod
Labels: trivial

#239 Move struct to internal header
  crypto/encode_decode/decoder_pkey.c
  crypto/evp/evp_local.h
  include/internal/evp.h
Labels: trivial
